CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users 
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""
SELECT_ID_QUERY = """
SELECT ID FROM telegram_users WHERE TELEGRAM_ID=?
"""
ALTER_TABLE_USER_QUERY_V1 = """
ALTER TABLE telegram_users ADD COLUMN REFERENCE_LINK TEXT
"""

ALTER_TABLE_USER_QUERY_V2 = """
ALTER TABLE telegram_users ADD COLUMN BALANCE INTEGER
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES(?,?,?,?,?,?,?)
"""

CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profiles 
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
PASSWORD TEXT,
DATA_OF_BIRTHDAY TEXT,
NICKNAME CHAR(50),
BIO CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_PROFILE_QUERY = """
INSERT INTO profiles VALUES(?,?,?,?,?,?,?)
"""

SELECT_ALL_PROFILES = """
SELECT * FROM profiles p 
WHERE p.TELEGRAM_ID NOT IN (
        SELECT ld.OWNER_TELEGRAM_ID
        FROM like_dislike ld
        WHERE ld.LIKER_TELEGRAM_ID = ?
        AND ld.LIKE_DISLIKE_STATUS IS NOT NULL
)
AND p.TELEGRAM_ID != ?
"""

CREATE_LIKE_DISLIKE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS like_dislike 
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
LIKER_TELEGRAM_ID INTEGER,
LIKE_DISLIKE_STATUS INTEGER,
UNIQUE (OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
)
"""

INSERT_LIKE_QUERY = """
INSERT INTO like_dislike VALUES(?,?,?,?)
"""

SELECT_PROFILE_QUERY = """
SELECT * FROM profiles WHERE TELEGRAM_ID = ?
"""

UPDATE_PROFILE_QUERY = """
UPDATE profiles SET NICKNAME = ?, BIO = ?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""

SELECT_USER_QUERY = """
SELECT * FROM telegram_users WHERE TELEGRAM_ID = ?
"""

SELECT_USER_BY_LINK_QUERY = """
SELECT * FROM telegram_users WHERE REFERENCE_LINK = ?
"""

CREATE_TABLE_REFERENCE_QUERY = """
CREATE TABLE IF NOT EXISTS reference
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
REFERENCE_TELEGRAM_ID INTEGER,
UNIQUE(OWNER_TELEGRAM_ID, REFERENCE_TELEGRAM_ID)
)
"""

INSERT_REFERENCE_USER_QUERY = """
INSERT INTO reference VALUES(?,?,?)
"""
SELECT_REFERENCE_QUERY = """
SELECT REFERENCE_TELEGRAM_ID FROM reference WHERE OWNER_TELEGRAM_ID = ?
"""

UPDATE_USER_LINK_QUERY = """
UPDATE telegram_users SET REFERENCE_LINK = ? WHERE TELEGRAM_ID = ?
"""

UPDATE_USER_BALANCE_QUERY = """
UPDATE telegram_users SET BALANCE = COALESCE(BALANCE, 0) + 100 WHERE TELEGRAM_ID = ?
"""

UPDATE_SENDER_BALANCE_QUERY = """
UPDATE telegram_users SET BALANCE = COALESCE(BALANCE, 0) - ? WHERE TELEGRAM_ID = ?
"""

UPDATE_RECIPIENT_BALANCE_QUERY = """
UPDATE telegram_users SET BALANCE = COALESCE(BALANCE, 0) + ? WHERE TELEGRAM_ID = ?
"""

CREATE_DONATE_TRANSACTIONS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS donate_transactions
(
ID INTEGER PRIMARY KEY,
SENDER_TELEGRAM_ID INTEGER,
RECIPIENT_TELEGRAM_ID INTEGER,
AMOUNT INTEGER
)
"""

INSERT_DONATE_TRANSACTIONS_QUERY = """
INSERT INTO donate_transactions VALUES(?,?,?,?)
"""

SELECT_LIKED_PROFILES = """
SELECT OWNER_TELEGRAM_ID 
FROM like_dislike 
WHERE LIKER_TELEGRAM_ID = ?
"""

CREATE_DONATE_CISTEM_QUERY = """
CREATE TABLE IF NOT EXISTS donate_cistem(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
SENDER_TELEGRAM_ID INTEGER,
)
"""

INSERT_DONATE_CISTEM_QUERY = """
INSERT INTO donate_cistem VALUES(?,?,?)
"""
