CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegrams_users (
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE(TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegrams_users VALUES (?,?,?,?,?)
"""

SELECT_USER_QUERY = """
SELECT FIRST_NAME FROM telegrams_users
"""

CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profiles
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
PASSWORD CHAR(50),
DATA_OF_BIRTHDAY CHAR(50),
BIO CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_PROFILE_QUERY = """
INSERT INTO profiles VALUES(?,?,?,?,?,?,?)
"""

SELECT_PROFILE_QUERY = """
SELECT * FROM profiles WHERE TELEGRAM_ID = ?
"""

CREATE_LIKE_DISLIKE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS like_dislike 
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
LIKER_TELEGRAM_ID INTEGER,
LIKE_DISLIKE_STATUS INTEGER,
UNIQUE (OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
)
"""

INSERT_LIKE_QUERY = """
INSERT INTO like_dislike VALUES(?,?,?,?)
"""


UPDATE_PROFILE_QUERY = """
UPDATE profiles SET NICKNAME = ?, BIO = ?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""

SELECT_ALL_PROFILES = """
SELECT * FROM profiles p 
WHERE p.TELEGRAM_ID NOT IN (
        SELECT ld.OWNER_TELEGRAM_ID
        FROM like_dislike ld
        WHERE ld.LIKER_TELEGRAM_ID = ?
        AND ld.LIKE_DISLIKE_STATUS IS NOT NULL
)
AND p.TELEGRAM_ID != ?
"""

DEL_MY_PROFILE = """
DELETE FROM profiles WHERE TELEGRAM_ID = ?
"""